#!/bin/bash
read -p "请输入想要发送的mina数量: " mina_amount
read -p "请输入想要使用的网络费用: " mina_fee
mkdir -p minasenderlogs
echo 解锁你的账户! $CODA_PUBLIC_KEY
coda account unlock -public-key $CODA_PUBLIC_KEY

IFS=$'\n';for MINA_ADDRESS in `cat mina_Users_address.txt`; do
coda client send-payment \
-amount $mina_amount \
-receiver ${MINA_ADDRESS} \
-fee $mina_fee \
-sender ${CODA_PUBLIC_KEY} | tee ./minasenderlogs/${MINA_ADDRESS}.log && sleep 10; done
